package rs.rbt.internship.admin.exception

enum class CsvMessageError(val message:String) {
    WRONG_CSV("WRONG CSV FILE"),
    WRONG_DATE_FORMAT("INVALID DATE FORMAT MUST BE IN DD/MM/YYYY"),
    WRONG_DATE("INVALID RANGE OF DATE SECOND DATE IS SMALLER THEN FIRST"),
    WRONG_CSV_ROW("WRONG ROW IN CSV FILE"),
    NOT_FOUND_EMPLOYEE("EMPLOYEE IS NOT FOUND"),
    WRONG_EMAIL_FORMAT("FORMAT FOR EMAIL IS NOT GOOD"),
    EMPLOYEE_EXISTS("EMPLOYEE EXISTS"),
    VACATION_DAYS_PER_YEAR_EXISTS("VACATION DAY PER YEAR ALREADY EXISTS"),
    USED_VACATION_EXISTS("VACATION ALREADY EXISTS"),
    ALL_VALID("ALL PARAMTETARS VALID")

}